### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by zerkz** [callawaycloud/lwc-json-view#20]
Hi, thanks for your LWC component here. 

I was wondering if you thought [about the license for this repository? ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository). 

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by ChuckJonas** [comment]
Added MIT to the repo.  Thanks!
